gpus: [0]

data:
  raw_directory: '/athena/sablab/scratch/mdo4009/NLST_nifti_manual/'
  annotations_dir: '/athena/sablab/scratch/mdo4009/Annotations - VT/'
  data_splits: '/athena/sablab/scratch/mdo4009/nnUNet-train_val_test-split.csv' #'/home/mdo4009/NLST-train_val_test-split.csv'
  batch_size_per_gpu: 2
  dataloader_workers_per_gpu: 1
  target_size: [ 256, 256, 256]

logging:
  root_path: 'logs_reconstruction'
  name: 'UNet3d_256'
  train_logs_steps: 100

model:
  name: 'UNet'

train:
  epochs: 200
  grad_clip: 10.0
  precision: 32
  lr: 1.0e-4
  loss:
    name: 'MSE'

  aug:
    name: 'basic3d'
