gpus: 0

data:
#  raw_directory: '/Users/mariadobko/Documents/Cornell/LAB/NLST_nifti/'
#  annotations_dir: '/Users/mariadobko/Downloads/Annotations - VT 3/'
#  data_splits: '/Users/mariadobko/Documents/Cornell/LAB/NLST-train_val_test-split.csv'
  raw_directory: '/athena/sablab/scratch/mdo4009/NLST_nifti/'
  annotations_dir: '/athena/sablab/scratch/mdo4009/Annotations - VT/'
  data_splits: '/home/mdo4009/NLST-train_val_test-split.csv'
  batch_size_per_gpu: 2
  dataloader_workers_per_gpu: 4
  target_size: [ 256, 256, 256 ]
  num_classes: 1

logging:
  root_path: 'logs'
  name: 'UNet'
  train_logs_steps: 100

model:
  name: 'UNet'
#  pretrained_weights: ''

train:
  epochs: 50
  grad_clip: 10.0
  precision: 32
  lr: 1.0e-4
  scheduler_gamma: 0.999994
  loss:
    name: 'DiceLoss'

  aug:
    name: 'basic3d'
