gpus: [1]

data:
  raw_directory: '/athena/sablab/scratch/mdo4009/NLST_nifti_manual/'
  annotations_dir: '/athena/sablab/scratch/mdo4009/Annotations - VT/'
  data_splits: '/home/mdo4009/NLST-train_val_test-split.csv'
  batch_size_per_gpu: 16
  dataloader_workers_per_gpu: 10
  target_size: [ 512, 512 ]
  num_classes: 1
  window_step: 1

logging:
  root_path: 'logs_clean'
  name: 'UNet_2-5D_window1'
  train_logs_steps: 500

model:
  name: 'UNet'

train:
  epochs: 150
  precision: 32
  lr: 1.0e-4
  loss:
    name: 'BCEWithLogitsLoss'
